
language: python

# Notification Preferences
notifications:
  email: false
  slack: weighin:LF7vfHWDvYn0Uijaoj6ZDg6e

# Set Test Versions
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"

# Set Environment Variables
env:
  - BUILD_ENV: dev
  - BUILD_ENV: prod
  - BUILD_ENV: prod_web
  - BUILD_ENV: prod_api

# Set Cache Options
cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages

# Install Dependencies
install:
  - "pip install -r requirements.txt --download-cache $HOME/.pip-cache"

# Run Tests
script: python manage.py test

# Deploy to Heroku Dev
deploy:
  provider: heroku
  strategy: api
  api_key: "bc7d0355-330e-4ca4-af3b-4d6055993b43"
  app:
    master: [weighin-app, api-weighin-app]
    develop: dev-weighin-app
  on:
    condition: "$BUILD_ENV = prod"
  run:
      - "python manage.py syncdb"